Marketplace vm solution v0.6.0
GoogleCloudPlatform/datashare-toolkit pull request #361
Opened 2020-10-28 14:03 UTC by swilliams11

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [X] Does your submission pass tests?
2. [X] Have you lint your code locally prior to submission?

Resolves #349

2020-10-28 14:04 UTC, swilliams11 commented
Fixes #349

2020-10-29 01:24 UTC, mservidio commented on marketplace/releases/RELEASE_NOTES_VM_SOLUTION.md
> +* Datashare release version is 0.5.0
Let's change to 0.5.1

2020-10-29 01:26 UTC, mservidio requested changes
Let's update the Datashare version to [0.5.1](https://github.com/GoogleCloudPlatform/datashare-toolkit/releases/tag/v0.5.1).

2020-10-29 13:33 UTC, swilliams11 commented
@mservidio Actually, its too late to change this.  Marketplace release 0.6.0 is already published to the Marketplace with v0.5.0, so I have to publish a new Marketplace release (v0.6.1) and have that point to the Datashare release version 0.5.1.

2020-10-30 01:27 UTC, mservidio approved these changes
LGTM

2020-10-30 15:43 UTC, merged